# Generated by Django 2.0.4 on 2018-04-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpp.Model'),
        ),
    ]
