# Generated by Django 2.0.4 on 2018-04-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0002_userpreference_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
    ]
