# Generated by Django 2.0.4 on 2018-06-05 16:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpp', '0008_auto_20180601_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_finish', models.DateField(default=datetime.date(2018, 8, 5))),
                ('car_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpp.CarProperties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
