# Generated by Django 2.0.4 on 2018-06-05 20:59

import cpp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0009_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperties',
            name='abc',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='abs',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='adaptive_cruise_control',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='adaptive_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='adjustable_steering_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='air_conditioning_analogue',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='air_conditioning_digital',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airbag_curtain',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airbag_driver',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airbag_knee',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airbag_passenger',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airbag_roof',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airbag_side',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='airmatic',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='alarm',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='allow_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='asr',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='auto_dimming_rearview_windows',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='automatic_folding_mirror',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='backup_camera',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='bas',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='bi_xenon_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='blind_spot_warning',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='bluetooth_or_phone',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='case_type',
            field=models.IntegerField(choices=[(0, 'Sedan'), (1, 'Hatchback')], default=0, verbose_name=cpp.models.CaseType),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='cd_changer',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='central_lock',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='chrome_plate',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='color',
            field=models.IntegerField(choices=[(0, 'White'), (1, 'Black'), (2, 'Blue'), (3, 'Red')], default=0, verbose_name=cpp.models.Color),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='cooled_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='cooled_torpedo',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='cruise_control',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='distronic',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='dvd_changer',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='eba',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='ebd',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='ebp',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='edl',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='electric_mirror',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='electric_rear_window',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='electric_windscreen',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='esp_or_vsa',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='exchange_status',
            field=models.IntegerField(choices=[(0, 'Unavaliable'), (1, 'Available')], default=0, verbose_name=cpp.models.ExchangeStatus),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='fabric_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='fatigue_detection',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='fog_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='folding_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='front_armrest',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='front_heated_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='front_parking_sensor',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='front_view_camera',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='fuel_type',
            field=models.IntegerField(choices=[(0, 'Gasoline'), (1, 'Diesel'), (2, 'Electricity'), (3, 'Hybrid')], default=0, verbose_name=cpp.models.FuelType),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='functional_steering_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='gear_type',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Automatic'), (2, 'Semi-automatic')], default=0, verbose_name=cpp.models.GearType),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='halogen_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='hardtop',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='head_up_display',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='heated_mirror',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='heated_steering_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='hill_start_assist',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='hydrolic_steering_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='immobilizer',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='ipod_connection',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='isofix',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='keyless_entry_and_run',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='lane_change_assist',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='lane_departure_warning',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='leather_or_fabric_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='leather_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='leather_steering_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='led_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='memory_mirror',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='memory_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='night_sensor_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='night_vision',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='owner_type',
            field=models.IntegerField(choices=[(0, 'By Owner'), (1, 'By Gallery')], default=0, verbose_name=cpp.models.OwnerType),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='panoramic_sunroof',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='panoramic_windscreen',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='power_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='radio_cd_player',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='radio_mp3_player',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='radio_tape_recorder',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='rain_sensor',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='rear_armrest',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='rear_entertainment_package',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='rear_heated_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='rear_parking_sensor',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='rear_window_defroster',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='repair_status',
            field=models.IntegerField(choices=[(0, 'Undamaged'), (1, 'Damage Recorded'), (2, 'Heavy Damage Recorded')], default=0, verbose_name=cpp.models.RepairStatus),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='seven_forward_gear',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='six_forward_gear',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='six_plus_speaker',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='smart_luggage_cover',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='start_stop',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='sunroof',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='tcs',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='third_row_seat',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='tire_defect_indicator',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='trailer_tow_bar',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='trip_computer',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='tv_or_navigation',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='usb_or_aux',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='washing_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='wooden_plate',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='wooden_steering_wheel',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='xenon_headlight',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Unimportant')], default=2),
        ),
    ]
