# Generated by Django 2.0.4 on 2018-06-05 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0010_auto_20180605_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperties',
            name='case_type',
            field=models.IntegerField(choices=[(0, 'Sedan'), (1, 'Hatchback')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='exchange_status',
            field=models.IntegerField(choices=[(0, 'Unavaliable'), (1, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='fuel_type',
            field=models.IntegerField(choices=[(0, 'Gasoline'), (1, 'Diesel'), (2, 'Electricity'), (3, 'Hybrid')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='gear_type',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Automatic'), (2, 'Semi-automatic')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='owner_type',
            field=models.IntegerField(choices=[(0, 'By Owner'), (1, 'By Gallery')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='repair_status',
            field=models.IntegerField(choices=[(0, 'Undamaged'), (1, 'Damage Recorded'), (2, 'Heavy Damage Recorded')], default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='date_finish',
            field=models.DateField(default=datetime.date(2018, 8, 6)),
        ),
    ]
