# Generated by Django 2.0.4 on 2018-06-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0011_auto_20180606_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperties',
            name='color',
            field=models.IntegerField(choices=[(0, 'White'), (1, 'Black'), (2, 'Blue'), (3, 'Red')], default=0),
        ),
    ]
