# Generated by Django 2.0.4 on 2018-06-06 10:22

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cpp', '0012_auto_20180606_0211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarProperties',
            new_name='CarProperty',
        ),
    ]
