# Generated by Django 2.0.4 on 2018-06-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0013_auto_20180606_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperty',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpp.Location'),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='case_type',
            field=models.IntegerField(choices=[(0, 'Sedan'), (1, 'Hatchback 3 Doors'), (2, 'Hatchback 5 Doors'), (3, 'Crossover'), (4, 'Roadster'), (4, 'Coupe'), (5, 'Station Wagon'), (6, 'Cabrio'), (7, 'MPV')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='color',
            field=models.IntegerField(choices=[(0, 'Black'), (1, 'Beige'), (2, 'Blue'), (3, 'Brown'), (4, 'Claret Red'), (5, 'Champagne'), (6, 'Gray'), (7, 'Green'), (8, 'Navy Blue'), (9, 'Orange'), (10, 'Pink'), (11, 'Purple'), (12, 'Red'), (13, 'Silver Gray'), (14, 'Smoke'), (15, 'Turquoise'), (16, 'White'), (17, 'Yellow')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='fuel_type',
            field=models.IntegerField(choices=[(0, 'Gasoline'), (1, 'Diesel'), (2, 'Gasoline and LPG'), (3, 'Electricity'), (4, 'Hybrid')], default=0),
        ),
    ]
