# Generated by Django 2.0.4 on 2018-06-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0014_auto_20180606_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangestatus',
            old_name='owner_type',
            new_name='exchange_status',
        ),
        migrations.RenameField(
            model_name='fueltype',
            old_name='fuel',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='geartype',
            old_name='gear',
            new_name='gear_type',
        ),
    ]
