# Generated by Django 2.0.4 on 2018-06-06 13:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpp', '0015_auto_20180606_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperty',
            name='date_finish',
            field=models.DateField(default=datetime.date(2018, 8, 6)),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
