# Generated by Django 2.0.4 on 2018-06-07 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0016_auto_20180606_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperty',
            name='date_finish',
            field=models.DateField(default=datetime.date(2018, 8, 7)),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='date_finish',
            field=models.DateField(default=datetime.date(2018, 8, 7)),
        ),
    ]
