# Generated by Django 2.0.4 on 2018-06-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpp', '0018_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperty',
            name='owner_type',
            field=models.IntegerField(choices=[(0, 'By Owner'), (1, 'By Gallery'), (2, 'By Authorized Dealer')], default=0),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpp.Power'),
        ),
    ]
